FORMAT: 1A
HOST: https://api.vogelhetuit.nl/v1

# Vogel het uit
The *Vogel het uit* service for sharing gps tracks (trips), assigning points of interest, attaching questions to poi, recieving answers and building trip story.

# Architecture

![Architecture](http://sverhoeven.github.io/vogelhetuit-api/Architecture.svg "Schema")

# Formatting

- Geo data must be in [GeoJSON](http://www.geojson.org) format.
- Timestamps must be in [ISO 8601](http://en.wikipedia.org/wiki/ISO_8601) (YYYY-MM-DDTHH:MM:SSZ) format.

# Authentication
Use Basic-authentication.
Not a all requests require authentication, when authentication is required it will be specified.

# Filtering

To filter a collection, you can append (? or &)&lt;property&gt;=&lt;value&gt; to the url.
The &lt;property&gt; should be the name of a field and &lt;value&gt; is the value you want to filter by.
Multiple filters can be used.
Filters which can't be specified using  &lt;property&gt;=&lt;value&gt; like spatial filters will be listed seperately.

# Pagination

For urls with collections use `page` query attribute (defaults to 1). The default pagesize is 10 and can be changed with `pagesize` query attribute.

Example on `/species?page=3&pagesize=20`:

+ Response 200 (application/json)

        {
            "total": 0,
            "items": []
        }

# Sorting

To sort a collection, you can append  ?order=&lt;field1&gt;,&lt;field2&gt; asc,&lt;field3&gt; desc.

# Multi lingual

The text fields which can be filled with this API should be made in the language for the target audience.
Any errors will be in English. The website/app is responsible to translate it for the user.

# Read-only attributes

The following attributes are read-only, when set during creating or update they will be silently ignored:
* The '_links' attribute is a way for hyperlinking between resources. The format used is HAL, see http://stateless.co/hal_specification.html.
* The '*_by' and '*_on' attributes are updated automaticly when a user performs a change to a resources.

# Group Species
A tracker is tied to an bird of a certain species.
Species can be used to filter birds, trips or stories.

## Species [/species/{id}]

+ Parameters
    + id (string) ... Species identifier.

+ Model (application/json)

        {
            "id": 8915,
            "latin_name": "Larus Fuscus",
            "common_name": {
                "nl": "Kleine mantelmeeuw",
                "en": "Lesser Black-backed gull"
            },
            "body": "<html describing species and why it is being researched>",
            "created_by": 3,
            "created_on": "2013-04-14T10:00:00Z"
        }

### Retrieve a species [GET]

+ Response 200

    [Species][]

### Update a species. [PUT]

+ Request

    [Species][]

+ Response 200

### Delete a species. [DELETE]

+ Response 204

## Species Collection [/species]

+ Model (application/json)

        {
            "total": 1234,
            "items":[{
                "id": 8915,
                "latin_name": "Larus Fuscus",
                "common_name": {
                    "nl": "Kleine mantelmeeuw",
                    "en": "Lesser Black-backed gull"
                },
                "body": "<html describing species and why it is being researched>",
                "created_by": 3,
                "created_on": "2013-04-14T10:00:00Z"
            }]
        }

### Retrieve list of species [GET]

+ Response 200

    [Species Collection][]

### Create a species. [POST]

+ Request

    [Species][]

+ Response 201

    + Headers

            Location: /species/8915

# Group Trips
A trip resource is set of timestamped coordinates with the eEcology tracker identifier.

## Trip [/trips/{id}]

+ Parameters
    + id (string) ... Trip identifier.

+ Model (application/json)

        {
            "id": 1,
            "species": 1,
            "tracker": 355,
            "start": "2013-04-14T10:00:00Z",
            "end": "2013-04-15T12:00:00Z",
            "body": "<html describing a trip>",
            "geo": {
                "type": "FeatureCollection",
                "bbox": [54.342, 12.543, 54.642, 12.543],
                "features": [{
                    "type": "Feature",
                    "geometry": {"type": "Point", "coordinates": [54.342, 12.543, -5]},
                    "properties": {"ts":  "2013-04-15T12:05:00Z"}
                }, {
                    "type": "Feature",
                    "geometry": {"type": "Point", "coordinates": [54.442, 12.543, -3]},
                    "properties": {"ts":  "2013-04-15T12:10:00Z"}
                }, {
                    "type": "Feature",
                    "geometry": {"type": "Point", "coordinates": [54.642, 12.543, -3]},
                    "properties": {"ts":  "2013-04-15T12:15:00Z"}
                }]
            },
            "is_visible": false,
            "created_by": 3,
            "created_on": "2013-04-14T10:00:00Z"
        }

### Retrieve a trip. [GET]

+ Response 200

    [Trip][]

### Update a trip. [PUT]

+ Request

    [Trip][]

+ Response 200

### Delete a trip. [DELETE]

+ Response 204

## Full trip [/trips/{id}/full]

### GET
Trip, but with Points of interests, Questions embedded into them. This is a shortcut instead of downloading a trip, loop over POIs, loop over questions.

+ Response 200 (application/json)

        {
            "id": 1,
            "species": 1,
            "tracker": 355,
            "start": "2013-04-14T10:00:00Z",
            "end": "2013-04-15T12:00:00Z",
            "body": "<html describing a trip>",
            "geo": {
                "type": "FeatureCollection",
                "bbox": [54.342, 12.543, 54.642, 12.543],
                "features": [{
                    "type": "Feature",
                    "geometry": {"type": "Point", "coordinates": [54.342, 12.543, -5]},
                    "properties": {"ts":  "2013-04-15T12:05:00Z"}
                }, {
                    "type": "Feature",
                    "geometry": {"type": "Point", "coordinates": [54.442, 12.543, -3]},
                    "properties": {"ts":  "2013-04-15T12:10:00Z"}
                }, {
                    "type": "Feature",
                    "geometry": {"type": "Point", "coordinates": [54.642, 12.543, -3]},
                    "properties": {"ts":  "2013-04-15T12:15:00Z"}
                }]
            },
            "pois": [{
                "id": 1,
                "location": {
                    "type": "Point",
                    "coordinates": [54.642, 12.543]
                },
                "radius": 100,
                "body": "<html describing motiviation for the poi>",
                "questions": [{
                    "id": 1,
                    "type": "radio, image or video or ...",
                    "title": "Question text",
                    "description" : "Description text",
                    "shortname": "Shortname or alias",
                    "other": true,  # When true adds 'Other' option, a short text field,
                    "options": [{
                        "title": "Title of option",
                        "value": "Value of option"
                    }],
                    "created_by": 3,
                    "created_on": "2013-04-14T10:00:00Z"
                }],
                "created_by": 3,
                "created_on": "2013-04-14T10:00:00Z"
            }],
            "is_visible": false,
            "created_by": 3,
            "created_on": "2013-04-14T10:00:00Z"
        }

## Trips [/trips]

+ Model (application/json)

        {
            "total": 12,
            "items": [{
                "id": 1,
                "species": 1,
                "tracker": 355,
                "start": "2013-04-14T10:00:00Z",
                "end": "2013-04-15T12:00:00Z",
                "body": "<html describing a trip>",
                "geo": {
                    "type": "FeatureCollection",
                    "bbox": [54.342, 12.543, 54.642, 12.543],
                    "features": [{
                        "type": "Feature",
                        "geometry": {"type": "Point", "coordinates": [54.342, 12.543, -5]},
                        "properties": {"ts":  "2013-04-15T12:05:00Z"}
                    }, {
                        "type": "Feature",
                        "geometry": {"type": "Point", "coordinates": [54.442, 12.543, -3]},
                        "properties": {"ts":  "2013-04-15T12:10:00Z"}
                    }, {
                        "type": "Feature",
                        "geometry": {"type": "Point", "coordinates": [54.642, 12.543, -3]},
                        "properties": {"ts":  "2013-04-15T12:15:00Z"}
                    }]
                },
                "is_visible": false,
                "created_by": 3,
                "created_on": "2013-04-14T10:00:00Z"
            }]
        }

### List of trips. [GET]

+ Response 200

    [Trips][]

### Create a trip. [POST]

The Trip resource requires the following attributes:

- tracker (string) ... Tracker identifier.
- start (string) ... Start time of trip.
- end (string) ... End time of trip.
- geo (GeoJSON) ... List of features that appear between start and end time.
- is_visible (boolean) ... Visiblility of trip. A hidden trip can only be seen by users with *researcher* role.

> TODO add visualization options, eg. color for speed, color for hour of day

+ Request

    [Trip][]

+ Response 201

    + Headers

            Location: /trips/1

## List of trips filtered on tracker [/trips?tracker={tracker}]

+ Parameters
    + tracker (string) ... A tracker identifier.

### GET

+ Response 200

    [Trips][]

## List of trips filtered on species [/trips?species={species}]

+ Parameters
    + species (string) ... A species identifier.

### GET

+ Response 200

    [Trips][]

# Group POIs
A point of interest is a place on a trip where a questions are connected to.

## Point of interest [/trips/{trip}/pois/{poi}]

+ Parameters
    + trip (string) ... Trip identifier.
    + poi (string) ... Point of interest identifier.

+ Model (application/json)

        {
            "id": 1,
            "location": {
                "type": "Point",
                "coordinates": [54.642, 12.543]
            },
            "radius": 100,
            "body": "<html describing motiviation for the poi>",
            "created_by": 3,
            "created_on": "2013-04-14T10:00:00Z"
        }

### Retrieve a POI [GET]

+ Response 200

    [Point of interest][]

### Update a POI [PUT]

+ Request

    [Point of interest][]

+ Response 200

## POIs [/pois]

Collection of point of interests.

+ Model (application/json)

        {
                "total": 1,
                "items": [{
                    "id": 1,
                    "trip": 1,
                    "location": {
                        "type": "Point",
                        "coordinates": [54.642, 12.543]
                    },
                    "radius": 100,
                    "distance": null,
                    "body": "<html describing motiviation for the poi>",
                    "created_by": 3,
                    "created_on": "2013-04-14T10:00:00Z"
                }]
        }

### List POIs [GET]

+ Response 200

    [POIs][]

## List of POIs filtered on geo bounding box [/pois?bbox={minlat},{minlon},{maxlat},{maxlon}]

+ Parameters
    + minlat (number) ... Minimum latitude
    + minlon (number) ... Minimum longitude
    + maxlat (number) ... Maximum latitude
    + maxlon (number) ... Maximum longitude

### GET

+ Response 200

    [POIs][]

## List of POIs ordered on distance from a location [/pois?dist={lat},{lon}]

Sets the distance field.

+ Parameters
    + lat (number) ... Latitude of location
    + lon (number) ... Longitude of location

### GET

+ Response 200

    [POIs][]

## List of POIs filtered on distance from a location [/pois?dist={lat},{lon}&radius={radius}]

Sets the distance field.

+ Parameters
    + lat (number) ... Latitude of location
    + lon (number) ... Longitude of location
    + radius (number) ... Radius in meters

### GET

+ Response 200

    [POIs][]

## List of POIs filtered on a tracker [/pois?tracker={tracker}]

+ Parameters
    + tracker (string) ... A tracker identifier

### GET

+ Response 200

    [POIs][]

## List of POIs ordered by newest POI first [/pois?sort=created_on]

### GET

+ Response 200

    [POIs][]

## Collection of points of interest of a trip [/trips/{trip}/pois]

+ Parameters
    + trip (string) ... Trip identifier.

### Create a point of interest [POST]

+ Request

    [Point of interest][]

+ Response 201

    + Headers

            Location: /trips/1/pois/1

### List points of interest for a trip [GET]

+ Response 200

    [POIs][]

# Group Questions
See http://manual.limesurvey.org/LimeSurvey_Manual for question types
and http://developer.surveygizmo.com/rest-api-documentation/objects/ for possible API.

## Question [/trips/{trip}/pois/{poi}/questions/{question}]

Types of questions:

- radio, multiple options with only one possible choice
- dropdown, a dropdown menu
- checkbox, multiple options with one or more possible choices
- text, short text field for an open question, this can be used as comment field.
- image, the answer value should be the url of the Media resource that was uploaded before submitting the answer.
- video, the answer value should be the url of the Media resource that was uploaded before submitting the answer.

+ Parameter
    + trip (string) ... Trip identifier.
    + poi (string) ... Point of interest identifier.
    + question (string) ... Question identifier

+ Model (application/json)

        {
            "id": 1,
            "type": "radio, image or video or ...",
            "title": "Question text",
            "description" : "Description text",
            "shortname": "Shortname or alias",
            "other": true,  # When true adds 'Other' option, a short text field,
            "options": [{
                "title": "Title of option",
                "value": "Value of option"
            }],
            "created_by": 3,
            "created_on": "2013-04-14T10:00:00Z"
        }

### Retrieve a question [GET]

+ Response 200

    [Question][]

### Update a question [PUT]

+ Request

    [Question][]

+ Response 200

## Questions [/trips/{trip}/pois/{poi}/questions]

+ Parameters
    + trip (string) ... Trip identifier.
    + poi (string) ... Point of interest identifier.

+ Model (application/json)

        {
            "total": 3,
            "items": [{
                "id": 1,
                "type": "radio, image or video or ...",
                "title": "Question text",
                "description" : "Description text",
                "shortname": "Shortname or alias",
                "other": true,  # When true adds 'Other' option, a short text field,
                "options": [{
                    "title": "Title of option",
                    "value": "Value of option"
                }],
                "created_by": 3,
                "created_on": "2013-04-14T10:00:00Z"
            }]
        }

### Create a question [POST]

+ Request

    [Question][]

+ Response 201

    + Headers

            Location: /trips/1/pois/1/questions/1

### List of questions [GET]

+ Response 200

    [Questions][]

## Question library [/questions]

### List of questions [GET]
Fetch list of questions independ of trip or poi.

+ Response 200

    [Questions][]

## Answer [/trips/{trip}/pois/{poi}/questions/{question}/answers/{answer}]

Attributes:

- answered_on, need to know when answer was given.
- location, need to know where answer was given.
- orientation, optional, heading or direction and tilting, used when question type is image or video otherwise ignored.
- value, the answer itself. For a media type answer it will be the url to the media.

+ Parameters
    + trip (string) ... Trip identifier.
    + poi (string) ... Point of interest identifier.
    + question (string) ... Question identifier.
    + answer (string) ... Answer identifier.

+ Model (application/json)

        {
            "id": 1,
            "lon": 54.642,
            "lat": 12.543,
            "head": 225.00,
            "tilt": 45.0,
            "value": "0",
            "answered_by": 32,
            "answered_on": "2013-09-04T12:30:00Z",
            "moderated_on": "2013-09-14T12:30:00Z",
            "moderated_by": 5
        }

### Retrieve an answer [GET]

Will only show answers to user who submitted answer or user with *researcher* role.

+ Response 200

    [Answer][]

## Moderate answer [/trips/{trip}/pois/{poi}/questions/{question}/answer/{answer}/moderate]

+ Parameters
    + trip (string) ... Trip identifier.
    + poi (string) ... Point of interest identifier.
    + question (string) ... Question identifier.
    + answer (string) ... Answer identifier.

### Approve answer [PUT]
Moderate media by approving it.

+ Response 204

### Disapprove answer [DELETE]
Moderate media by disapproving it.
This will delete the answer and if question type is image or video will also delete the uploaded media.

+ Response 204

## Answers [/trips/{trip}/pois/{poi}/questions/{question}/answers]

+ Parameters
    + trip (string) ... Trip identifier.
    + poi (string) ... Point of interest identifier.
    + question (string) ... Question identifier

+ Model (application/json)

        {
            "total": 5000,
            "items": [{
                "id": 1,
                "timestamp": "2013-05-14T12:30:00Z",
                "lon": 54.642,
                "lat": 12.543,
                "head": 225.00,
                "tilt": 45.0,
                "value": "0",
                "answered_by": 32,
                "answered_on": "2013-09-04T12:30:00Z",
                "moderated_on": "2013-09-14T12:30:00Z",
                "moderated_by": 5
            }]
        }

### Retrieve answers for a question [GET]

Will only show answers to user who submitted answer or user with *researcher* role.

+ Response 200

    [Answers][]

### Create an answer [POST]

Answers can contain a media file like a image or video, this prevents using a normal POST body with json os use file upload form submission.

Answers without media use *application/x-www-form-urlencoded* content type with the `json` form field, see first request.
Answers with media use *multipart/form-data* content type with the `json` and `media` form fields, see second request.

The `json` form field is a json encoded string of the Answer resource.

If answer send media then in the response the answer value will be the url where the media can be downloaded.

+ Request (application/x-www-form-urlencoded; charset=utf-8)

    json=%7B%0A++++%22value%22%3A+%22some+answer%22%2C%0A++++%22lon%22%3A+54.642%2C%0A++++%22lat%22%3A+12.543%2C%0A++++%22answered_on%22%3A+%222013-09-04T12%3A30%3A00Z%22%0A%7D%0A

+ Request (multipart/form-data;boundary=AaB03x)

        --AaB03x
        Content-Disposition: form-data; name="json"
        Content-Type: application/json

        {
            "value": "some answer",
            "lon": 54.642,
            "lat": 12.543,
            "head": 225.00,
            "tilt": 45.0,
            "answered_on": "2013-09-04T12:30:00Z"
        }
        --AaB03x
        Content-Disposition: form-data; name="media"; filename="image1.png"
        Content-Type: image/png

        ... content of image1.png

        --AaB03x

+ Response 201

    [Answer][]

## Unmoderated answers for question [/trips/1/pois/1/questions/1/answers/unmoderated]

+ Parameters
    + trip (string) ... Trip identifier.
    + poi (string) ... Point of interest identifier.
    + question (string) ... Question identifier.
    + answer (string) ... Answer identifier.

### Retrieve unmoderated answers [GET]

Will only show answers to user who submitted answer or user with *moderator* role.

+ Response 200

    [Answers][]

## All unmoderated answers [/answers/unmoderated]

### Retrieve unmoderated answers [GET]

Will only show answers to user who submitted answer or user with *moderator* role.

+ Response 200

    [Answers][]

# Group Stories
A story is about a trip and it's POIs combined with the supplied answers and insight of researcher.

## Story [/stories/{id}]

+ Parameters
    + id (string) ... Story identifier

+ Model (application/json)

        {
            "id": 1,
            "trip": 1,
            "title": "Title of story",
            "body": "<html of story>",
            "is_visible": "Boolean whether story should be visible",
            "created_by": 3,
            "created_on": "2013-04-14T10:00:00Z"
        }

### Get a story [GET]

+ Response 200

    [Story][]

### Update a story [PUT]

+ Request

    [Story][]

+ Response 204

## Stories [/stories]

+ Model (application/json)

        {
            "total": 15,
            "items": [{
                "id": "1",
                "trip": "1",
                "title": "Title of story",
                "body": "<html of story>",
                "is_visible": "Boolean whether story should be visible",
                "created_by": 3,
                "created_on": "2013-04-14T10:00:00Z"
            }]
        }


### Create a story [POST]

+ Request

    [Story][]

+ Response 201

    + Headers

            Location: /stories/1

### List of stories [GET]

+ Response 200

    [Stories][]

## List of stories filtered by species [/stories?species={species}]

### GET

+ Response 200

    [Stories][]

## List of stories filtered by bird [/stories?bird={bird}]

### GET

+ Response 200

    [Stories][]

# Group Users
User administration and profile.

Roles:

- anonymous, can answer questions, but can not change anything else (this includes submitting comments and media).
- registered, can answer questions, submit comments and media. Can also see in his/her profile the work he/she done.
- moderator, can see answers of everyone and delete answers. Same for comments and media.
- researcher, can fetch tracks and create a trip, poi, questions and a story.
- administrator, can assign roles to users.

## Roles [/roles]

+ Model (application/json)

        {
            "total": 5,
            "items": [
                "anonymous",
                "registered",
                "moderator",
                "researcher",
                "administrator"
            }]
        }

### List of roles [GET]

+ Response 200

    [Roles][]

## User [/users/{user}]

The `password` and `password_verify` are only required during creation and update. They will not be retrieved.

+ Parameters
    + user (string) ... User identifier.

+ Model (application/json)

        {
            "id": 3,
            "username": "User chosen username",
            "password": "Password",
            "password_verify": "Password verification",
            "email": "e-mail adres of user",
            "phone": "(Mobile) phone number, used by researcher to ask feedback",
            "roles": "registered",
            "created_on": "2013-04-14T10:00:00Z"
        }


### Retrieve a user [GET]

Only retrievable by user with the *administrator* role.

+ Response 200

    [User][]

### Update a user [PUT]

+ Request

    [User][]

+ Response 201

### Deleta a user [DELETE]

+ Response 204

## Self [/users/self]

### User information of authenticated user [GET]

+ Response 200

    [User][]

## Collection of users [/users]

### Create a user [POST]

A created user will automaticly get the *registered* role.

+ Request

    [User][]

+ Response 201

    + Headers

            Location: /users/1

### List of users [GET]

Only retrievable by user with the *administrator* role.

+ Response 200 (application/json)

        {
            "total": 100,
            "items": [{
                "id": 3,
                "username": "User chosen username",
                "email": "e-mail adres of user",
                "phone": "(Mobile) phone number, used by researcher to ask feedback",
                "role": "researcher",
                "created_on": "2013-04-14T10:00:00Z"
            }]
        }

## Relation of user and role [/users/{user}/roles/{role}]

Role can be set to a user by a user with the *administrator* role.

+ Parameters
    + user (string) ... User identifier.
    + role (string) ... Role identifier.

### Set role of user [PUT]

+ Response 204
